name: Create JSON

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        curl -o colornames.txt https://colornames.org/download/generate.php
        node .
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Color Files JSON
        path: assets/colornames.json
      env:
        CI: true
